# Generated by Django 5.2.8 on 2026-04-25 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_advanced_form', '0002_alter_condition_operator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='operator',
            field=models.CharField(choices=[('empty', 'Is Empty'), ('not_empty', 'Is Not Empty'), ('equals', '='), ('not_equals', '!='), ('gt', '>'), ('gte', '>='), ('lt', '<'), ('lte', '<=')], max_length=20, verbose_name='Rule'),
        ),
    ]
