# Generated by Django 5.2.8 on 2026-04-27 04:25

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_advanced_form', '0003_alter_condition_operator'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancedformpage',
            name='autoresponder_content',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='advancedformpage',
            name='autoresponder_from_email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='advancedformpage',
            name='autoresponder_subject',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='formfield',
            name='autoresponder_email_field',
            field=models.BooleanField(default=False, verbose_name='Autoresponder email field'),
        ),
        migrations.AddField(
            model_name='formfield',
            name='autoresponder_first_name_field',
            field=models.BooleanField(default=False, verbose_name='Autoresponder first name field'),
        ),
        migrations.AddField(
            model_name='formfield',
            name='autoresponder_last_name_field',
            field=models.BooleanField(default=False, verbose_name='Autoresponder last name field'),
        ),
        migrations.AddField(
            model_name='formfield',
            name='autoresponder_salutation_field',
            field=models.BooleanField(default=False, verbose_name='Autoresponder salutation field'),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='field_type',
            field=models.CharField(choices=[('singleline', 'Single line text'), ('multiline', 'Multi-line text'), ('email', 'Email'), ('number', 'Number'), ('url', 'URL'), ('checkbox', 'Checkbox'), ('checkboxes', 'Checkboxes'), ('dropdown', 'Drop down'), ('multiselect', 'Multiple select'), ('radio', 'Radio buttons'), ('date', 'Date'), ('datetime', 'Date/time'), ('hidden', 'Hidden field'), ('image', 'Upload Image'), ('document', 'File Upload'), ('heading', 'Heading')], max_length=16, verbose_name='field type'),
        ),
    ]
