# Generated by Django 5.2.8 on 2026-04-27 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_advanced_form', '0004_advancedformpage_autoresponder_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfield',
            name='condition_logic',
            field=models.CharField(choices=[('and', 'Match ALL conditions (AND)'), ('or', 'Match ANY condition (OR)')], default='and', help_text='How multiple conditions should be evaluated', max_length=3),
        ),
    ]
